extends = "vendor/php-db/phpdb-qa-tools/mago.toml"
php-version = "8.3.0"

[source]
paths = ["src", "test"]
includes = ["vendor"]

[formatter]
parentheses-around-new-in-member-access = true

[linter]
baseline = "lint-baseline.toml"

[analyzer]
baseline = "analyzer-baseline.toml"
class-initializers = [
    "PhpDb\\ResultSet\\AbstractResultSet::initialize",
    "PhpDb\\TableGateway\\Feature\\AbstractFeature::setTableGateway",
    "PhpDb\\RowGateway\\Feature\\AbstractFeature::setRowGateway",
    "PhpDb\\Sql\\Platform\\AbstractPlatform::setSubject",
]
