name: CI

on:
  push:
  pull_request:

jobs:
  qa:
    uses: php-db/phpdb-qa-tools/.github/workflows/qa.yml@0.1.x
    with:
      php-versions: '["8.2", "8.3", "8.4", "8.5"]'
      run-integration: false
